// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VersionClient.proto

package org.locationtech.geowave.datastore.hbase.query.protobuf;

public final class VersionProtosClient {
  private VersionProtosClient() {}
  public static void registerAllExtensions(
      org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VersionRequestOrBuilder
      extends org.apache.hadoop.hbase.shaded.com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code VersionRequest}
   */
  public static final class VersionRequest extends
      org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage
      implements VersionRequestOrBuilder {
    // Use VersionRequest.newBuilder() to construct.
    private VersionRequest(org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VersionRequest(boolean noInit) { this.unknownFields = org.apache.hadoop.hbase.shaded.com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VersionRequest defaultInstance;
    public static VersionRequest getDefaultInstance() {
      return defaultInstance;
    }

    public VersionRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final org.apache.hadoop.hbase.shaded.com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final org.apache.hadoop.hbase.shaded.com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VersionRequest(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedInputStream input,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      org.apache.hadoop.hbase.shaded.com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          org.apache.hadoop.hbase.shaded.com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.internal_static_VersionRequest_descriptor;
    }

    protected org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.internal_static_VersionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest.class, org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest.Builder.class);
    }

    public static org.apache.hadoop.hbase.shaded.com.google.protobuf.Parser<VersionRequest> PARSER =
        new org.apache.hadoop.hbase.shaded.com.google.protobuf.AbstractParser<VersionRequest>() {
      public VersionRequest parsePartialFrom(
          org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedInputStream input,
          org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
        return new VersionRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.Parser<VersionRequest> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest)) {
        return super.equals(obj);
      }
      org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest other = (org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest) obj;

      boolean result = true;
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest parseFrom(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString data)
        throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest parseFrom(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString data,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest parseFrom(byte[] data)
        throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest parseFrom(
        byte[] data,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest parseFrom(
        java.io.InputStream input,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest parseDelimitedFrom(
        java.io.InputStream input,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest parseFrom(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest parseFrom(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedInputStream input,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VersionRequest}
     */
    public static final class Builder extends
        org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequestOrBuilder {
      public static final org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.internal_static_VersionRequest_descriptor;
      }

      protected org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.internal_static_VersionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest.class, org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest.Builder.class);
      }

      // Construct using org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.internal_static_VersionRequest_descriptor;
      }

      public org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest getDefaultInstanceForType() {
        return org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest.getDefaultInstance();
      }

      public org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest build() {
        org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest buildPartial() {
        org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest result = new org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(org.apache.hadoop.hbase.shaded.com.google.protobuf.Message other) {
        if (other instanceof org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest) {
          return mergeFrom((org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest other) {
        if (other == org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedInputStream input,
          org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:VersionRequest)
    }

    static {
      defaultInstance = new VersionRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:VersionRequest)
  }

  public interface VersionResponseOrBuilder
      extends org.apache.hadoop.hbase.shaded.com.google.protobuf.MessageOrBuilder {

    // repeated string versionInfo = 1;
    /**
     * <code>repeated string versionInfo = 1;</code>
     */
    java.util.List<java.lang.String>
    getVersionInfoList();
    /**
     * <code>repeated string versionInfo = 1;</code>
     */
    int getVersionInfoCount();
    /**
     * <code>repeated string versionInfo = 1;</code>
     */
    java.lang.String getVersionInfo(int index);
    /**
     * <code>repeated string versionInfo = 1;</code>
     */
    org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString
        getVersionInfoBytes(int index);
  }
  /**
   * Protobuf type {@code VersionResponse}
   */
  public static final class VersionResponse extends
      org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage
      implements VersionResponseOrBuilder {
    // Use VersionResponse.newBuilder() to construct.
    private VersionResponse(org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VersionResponse(boolean noInit) { this.unknownFields = org.apache.hadoop.hbase.shaded.com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VersionResponse defaultInstance;
    public static VersionResponse getDefaultInstance() {
      return defaultInstance;
    }

    public VersionResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final org.apache.hadoop.hbase.shaded.com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final org.apache.hadoop.hbase.shaded.com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VersionResponse(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedInputStream input,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      org.apache.hadoop.hbase.shaded.com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          org.apache.hadoop.hbase.shaded.com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                versionInfo_ = new org.apache.hadoop.hbase.shaded.com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              versionInfo_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          versionInfo_ = new org.apache.hadoop.hbase.shaded.com.google.protobuf.UnmodifiableLazyStringList(versionInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.internal_static_VersionResponse_descriptor;
    }

    protected org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.internal_static_VersionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse.class, org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse.Builder.class);
    }

    public static org.apache.hadoop.hbase.shaded.com.google.protobuf.Parser<VersionResponse> PARSER =
        new org.apache.hadoop.hbase.shaded.com.google.protobuf.AbstractParser<VersionResponse>() {
      public VersionResponse parsePartialFrom(
          org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedInputStream input,
          org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
        return new VersionResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.Parser<VersionResponse> getParserForType() {
      return PARSER;
    }

    // repeated string versionInfo = 1;
    public static final int VERSIONINFO_FIELD_NUMBER = 1;
    private org.apache.hadoop.hbase.shaded.com.google.protobuf.LazyStringList versionInfo_;
    /**
     * <code>repeated string versionInfo = 1;</code>
     */
    public java.util.List<java.lang.String>
        getVersionInfoList() {
      return versionInfo_;
    }
    /**
     * <code>repeated string versionInfo = 1;</code>
     */
    public int getVersionInfoCount() {
      return versionInfo_.size();
    }
    /**
     * <code>repeated string versionInfo = 1;</code>
     */
    public java.lang.String getVersionInfo(int index) {
      return versionInfo_.get(index);
    }
    /**
     * <code>repeated string versionInfo = 1;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString
        getVersionInfoBytes(int index) {
      return versionInfo_.getByteString(index);
    }

    private void initFields() {
      versionInfo_ = org.apache.hadoop.hbase.shaded.com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < versionInfo_.size(); i++) {
        output.writeBytes(1, versionInfo_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < versionInfo_.size(); i++) {
          dataSize += org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(versionInfo_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getVersionInfoList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse)) {
        return super.equals(obj);
      }
      org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse other = (org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse) obj;

      boolean result = true;
      result = result && getVersionInfoList()
          .equals(other.getVersionInfoList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getVersionInfoCount() > 0) {
        hash = (37 * hash) + VERSIONINFO_FIELD_NUMBER;
        hash = (53 * hash) + getVersionInfoList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse parseFrom(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString data)
        throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse parseFrom(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString data,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse parseFrom(byte[] data)
        throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse parseFrom(
        byte[] data,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse parseFrom(
        java.io.InputStream input,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse parseDelimitedFrom(
        java.io.InputStream input,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse parseFrom(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse parseFrom(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedInputStream input,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VersionResponse}
     */
    public static final class Builder extends
        org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponseOrBuilder {
      public static final org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.internal_static_VersionResponse_descriptor;
      }

      protected org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.internal_static_VersionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse.class, org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse.Builder.class);
      }

      // Construct using org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        versionInfo_ = org.apache.hadoop.hbase.shaded.com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.internal_static_VersionResponse_descriptor;
      }

      public org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse getDefaultInstanceForType() {
        return org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse.getDefaultInstance();
      }

      public org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse build() {
        org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse buildPartial() {
        org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse result = new org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          versionInfo_ = new org.apache.hadoop.hbase.shaded.com.google.protobuf.UnmodifiableLazyStringList(
              versionInfo_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.versionInfo_ = versionInfo_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(org.apache.hadoop.hbase.shaded.com.google.protobuf.Message other) {
        if (other instanceof org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse) {
          return mergeFrom((org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse other) {
        if (other == org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse.getDefaultInstance()) return this;
        if (!other.versionInfo_.isEmpty()) {
          if (versionInfo_.isEmpty()) {
            versionInfo_ = other.versionInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureVersionInfoIsMutable();
            versionInfo_.addAll(other.versionInfo_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedInputStream input,
          org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated string versionInfo = 1;
      private org.apache.hadoop.hbase.shaded.com.google.protobuf.LazyStringList versionInfo_ = org.apache.hadoop.hbase.shaded.com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureVersionInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          versionInfo_ = new org.apache.hadoop.hbase.shaded.com.google.protobuf.LazyStringArrayList(versionInfo_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string versionInfo = 1;</code>
       */
      public java.util.List<java.lang.String>
          getVersionInfoList() {
        return java.util.Collections.unmodifiableList(versionInfo_);
      }
      /**
       * <code>repeated string versionInfo = 1;</code>
       */
      public int getVersionInfoCount() {
        return versionInfo_.size();
      }
      /**
       * <code>repeated string versionInfo = 1;</code>
       */
      public java.lang.String getVersionInfo(int index) {
        return versionInfo_.get(index);
      }
      /**
       * <code>repeated string versionInfo = 1;</code>
       */
      public org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString
          getVersionInfoBytes(int index) {
        return versionInfo_.getByteString(index);
      }
      /**
       * <code>repeated string versionInfo = 1;</code>
       */
      public Builder setVersionInfo(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureVersionInfoIsMutable();
        versionInfo_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string versionInfo = 1;</code>
       */
      public Builder addVersionInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureVersionInfoIsMutable();
        versionInfo_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string versionInfo = 1;</code>
       */
      public Builder addAllVersionInfo(
          java.lang.Iterable<java.lang.String> values) {
        ensureVersionInfoIsMutable();
        super.addAll(values, versionInfo_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string versionInfo = 1;</code>
       */
      public Builder clearVersionInfo() {
        versionInfo_ = org.apache.hadoop.hbase.shaded.com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string versionInfo = 1;</code>
       */
      public Builder addVersionInfoBytes(
          org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureVersionInfoIsMutable();
        versionInfo_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:VersionResponse)
    }

    static {
      defaultInstance = new VersionResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:VersionResponse)
  }

  /**
   * Protobuf service {@code VersionService}
   */
  public static abstract class VersionService
      implements org.apache.hadoop.hbase.shaded.com.google.protobuf.Service {
    protected VersionService() {}

    public interface Interface {
      /**
       * <code>rpc version(.VersionRequest) returns (.VersionResponse);</code>
       */
      public abstract void version(
          org.apache.hadoop.hbase.shaded.com.google.protobuf.RpcController controller,
          org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest request,
          org.apache.hadoop.hbase.shaded.com.google.protobuf.RpcCallback<org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse> done);

    }

    public static org.apache.hadoop.hbase.shaded.com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new VersionService() {
        @java.lang.Override
        public  void version(
            org.apache.hadoop.hbase.shaded.com.google.protobuf.RpcController controller,
            org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest request,
            org.apache.hadoop.hbase.shaded.com.google.protobuf.RpcCallback<org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse> done) {
          impl.version(controller, request, done);
        }

      };
    }

    public static org.apache.hadoop.hbase.shaded.com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new org.apache.hadoop.hbase.shaded.com.google.protobuf.BlockingService() {
        public final org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final org.apache.hadoop.hbase.shaded.com.google.protobuf.Message callBlockingMethod(
            org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.MethodDescriptor method,
            org.apache.hadoop.hbase.shaded.com.google.protobuf.RpcController controller,
            org.apache.hadoop.hbase.shaded.com.google.protobuf.Message request)
            throws org.apache.hadoop.hbase.shaded.com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.version(controller, (org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final org.apache.hadoop.hbase.shaded.com.google.protobuf.Message
            getRequestPrototype(
            org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final org.apache.hadoop.hbase.shaded.com.google.protobuf.Message
            getResponsePrototype(
            org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc version(.VersionRequest) returns (.VersionResponse);</code>
     */
    public abstract void version(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.RpcController controller,
        org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest request,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.RpcCallback<org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse> done);

    public static final
        org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.getDescriptor().getServices().get(0);
    }
    public final org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.MethodDescriptor method,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.RpcController controller,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.Message request,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.RpcCallback<
          org.apache.hadoop.hbase.shaded.com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.version(controller, (org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest)request,
            org.apache.hadoop.hbase.shaded.com.google.protobuf.RpcUtil.<org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final org.apache.hadoop.hbase.shaded.com.google.protobuf.Message
        getRequestPrototype(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final org.apache.hadoop.hbase.shaded.com.google.protobuf.Message
        getResponsePrototype(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionService implements Interface {
      private Stub(org.apache.hadoop.hbase.shaded.com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final org.apache.hadoop.hbase.shaded.com.google.protobuf.RpcChannel channel;

      public org.apache.hadoop.hbase.shaded.com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void version(
          org.apache.hadoop.hbase.shaded.com.google.protobuf.RpcController controller,
          org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest request,
          org.apache.hadoop.hbase.shaded.com.google.protobuf.RpcCallback<org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse.getDefaultInstance(),
          org.apache.hadoop.hbase.shaded.com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse.class,
            org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse version(
          org.apache.hadoop.hbase.shaded.com.google.protobuf.RpcController controller,
          org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest request)
          throws org.apache.hadoop.hbase.shaded.com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(org.apache.hadoop.hbase.shaded.com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final org.apache.hadoop.hbase.shaded.com.google.protobuf.BlockingRpcChannel channel;

      public org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse version(
          org.apache.hadoop.hbase.shaded.com.google.protobuf.RpcController controller,
          org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionRequest request)
          throws org.apache.hadoop.hbase.shaded.com.google.protobuf.ServiceException {
        return (org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.locationtech.geowave.datastore.hbase.query.protobuf.VersionProtosClient.VersionResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:VersionService)
  }

  private static org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.Descriptor
    internal_static_VersionRequest_descriptor;
  private static
    org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VersionRequest_fieldAccessorTable;
  private static org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.Descriptor
    internal_static_VersionResponse_descriptor;
  private static
    org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VersionResponse_fieldAccessorTable;

  public static org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023VersionClient.proto\"\020\n\016VersionRequest\"" +
      "&\n\017VersionResponse\022\023\n\013versionInfo\030\001 \003(\t2" +
      ">\n\016VersionService\022,\n\007version\022\017.VersionRe" +
      "quest\032\020.VersionResponseBV\n7org.locationt" +
      "ech.geowave.datastore.hbase.query.protob" +
      "ufB\023VersionProtosClientH\001\210\001\001\240\001\001"
    };
    org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistry assignDescriptors(
            org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_VersionRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_VersionRequest_fieldAccessorTable = new
            org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_VersionRequest_descriptor,
              new java.lang.String[] { });
          internal_static_VersionResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_VersionResponse_fieldAccessorTable = new
            org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_VersionResponse_descriptor,
              new java.lang.String[] { "VersionInfo", });
          return null;
        }
      };
    org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
