// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SingleEntryFiltersClient.proto

package org.locationtech.geowave.datastore.hbase.coprocessors.protobuf;

public final class FilterProtosClient {
  private FilterProtosClient() {}
  public static void registerAllExtensions(
      org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SingleEntryFilterOrBuilder
      extends org.apache.hadoop.hbase.shaded.com.google.protobuf.MessageOrBuilder {

    // required bytes adapterId = 1;
    /**
     * <code>required bytes adapterId = 1;</code>
     */
    boolean hasAdapterId();
    /**
     * <code>required bytes adapterId = 1;</code>
     */
    org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString getAdapterId();

    // required bytes dataId = 2;
    /**
     * <code>required bytes dataId = 2;</code>
     */
    boolean hasDataId();
    /**
     * <code>required bytes dataId = 2;</code>
     */
    org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString getDataId();
  }
  /**
   * Protobuf type {@code SingleEntryFilter}
   */
  public static final class SingleEntryFilter extends
      org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage
      implements SingleEntryFilterOrBuilder {
    // Use SingleEntryFilter.newBuilder() to construct.
    private SingleEntryFilter(org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SingleEntryFilter(boolean noInit) { this.unknownFields = org.apache.hadoop.hbase.shaded.com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SingleEntryFilter defaultInstance;
    public static SingleEntryFilter getDefaultInstance() {
      return defaultInstance;
    }

    public SingleEntryFilter getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final org.apache.hadoop.hbase.shaded.com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final org.apache.hadoop.hbase.shaded.com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SingleEntryFilter(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedInputStream input,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      org.apache.hadoop.hbase.shaded.com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          org.apache.hadoop.hbase.shaded.com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              adapterId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              dataId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.internal_static_SingleEntryFilter_descriptor;
    }

    protected org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.internal_static_SingleEntryFilter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter.class, org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter.Builder.class);
    }

    public static org.apache.hadoop.hbase.shaded.com.google.protobuf.Parser<SingleEntryFilter> PARSER =
        new org.apache.hadoop.hbase.shaded.com.google.protobuf.AbstractParser<SingleEntryFilter>() {
      public SingleEntryFilter parsePartialFrom(
          org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedInputStream input,
          org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
        return new SingleEntryFilter(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.Parser<SingleEntryFilter> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes adapterId = 1;
    public static final int ADAPTERID_FIELD_NUMBER = 1;
    private org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString adapterId_;
    /**
     * <code>required bytes adapterId = 1;</code>
     */
    public boolean hasAdapterId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes adapterId = 1;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString getAdapterId() {
      return adapterId_;
    }

    // required bytes dataId = 2;
    public static final int DATAID_FIELD_NUMBER = 2;
    private org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString dataId_;
    /**
     * <code>required bytes dataId = 2;</code>
     */
    public boolean hasDataId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes dataId = 2;</code>
     */
    public org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString getDataId() {
      return dataId_;
    }

    private void initFields() {
      adapterId_ = org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString.EMPTY;
      dataId_ = org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAdapterId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDataId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, adapterId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, dataId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, adapterId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, dataId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter)) {
        return super.equals(obj);
      }
      org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter other = (org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter) obj;

      boolean result = true;
      result = result && (hasAdapterId() == other.hasAdapterId());
      if (hasAdapterId()) {
        result = result && getAdapterId()
            .equals(other.getAdapterId());
      }
      result = result && (hasDataId() == other.hasDataId());
      if (hasDataId()) {
        result = result && getDataId()
            .equals(other.getDataId());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasAdapterId()) {
        hash = (37 * hash) + ADAPTERID_FIELD_NUMBER;
        hash = (53 * hash) + getAdapterId().hashCode();
      }
      if (hasDataId()) {
        hash = (37 * hash) + DATAID_FIELD_NUMBER;
        hash = (53 * hash) + getDataId().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter parseFrom(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString data)
        throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter parseFrom(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString data,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter parseFrom(byte[] data)
        throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter parseFrom(
        byte[] data,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter parseFrom(
        java.io.InputStream input,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter parseDelimitedFrom(
        java.io.InputStream input,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter parseFrom(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter parseFrom(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedInputStream input,
        org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SingleEntryFilter}
     */
    public static final class Builder extends
        org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilterOrBuilder {
      public static final org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.internal_static_SingleEntryFilter_descriptor;
      }

      protected org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.internal_static_SingleEntryFilter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter.class, org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter.Builder.class);
      }

      // Construct using org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        adapterId_ = org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        dataId_ = org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.internal_static_SingleEntryFilter_descriptor;
      }

      public org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter getDefaultInstanceForType() {
        return org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter.getDefaultInstance();
      }

      public org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter build() {
        org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter buildPartial() {
        org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter result = new org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.adapterId_ = adapterId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dataId_ = dataId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(org.apache.hadoop.hbase.shaded.com.google.protobuf.Message other) {
        if (other instanceof org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter) {
          return mergeFrom((org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter other) {
        if (other == org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter.getDefaultInstance()) return this;
        if (other.hasAdapterId()) {
          setAdapterId(other.getAdapterId());
        }
        if (other.hasDataId()) {
          setDataId(other.getDataId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAdapterId()) {
          
          return false;
        }
        if (!hasDataId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          org.apache.hadoop.hbase.shaded.com.google.protobuf.CodedInputStream input,
          org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (org.apache.hadoop.hbase.shaded.com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.locationtech.geowave.datastore.hbase.coprocessors.protobuf.FilterProtosClient.SingleEntryFilter) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes adapterId = 1;
      private org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString adapterId_ = org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes adapterId = 1;</code>
       */
      public boolean hasAdapterId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes adapterId = 1;</code>
       */
      public org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString getAdapterId() {
        return adapterId_;
      }
      /**
       * <code>required bytes adapterId = 1;</code>
       */
      public Builder setAdapterId(org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        adapterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes adapterId = 1;</code>
       */
      public Builder clearAdapterId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        adapterId_ = getDefaultInstance().getAdapterId();
        onChanged();
        return this;
      }

      // required bytes dataId = 2;
      private org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString dataId_ = org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes dataId = 2;</code>
       */
      public boolean hasDataId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes dataId = 2;</code>
       */
      public org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString getDataId() {
        return dataId_;
      }
      /**
       * <code>required bytes dataId = 2;</code>
       */
      public Builder setDataId(org.apache.hadoop.hbase.shaded.com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dataId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes dataId = 2;</code>
       */
      public Builder clearDataId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dataId_ = getDefaultInstance().getDataId();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SingleEntryFilter)
    }

    static {
      defaultInstance = new SingleEntryFilter(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SingleEntryFilter)
  }

  private static org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.Descriptor
    internal_static_SingleEntryFilter_descriptor;
  private static
    org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SingleEntryFilter_fieldAccessorTable;

  public static org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036SingleEntryFiltersClient.proto\"6\n\021Sing" +
      "leEntryFilter\022\021\n\tadapterId\030\001 \002(\014\022\016\n\006data" +
      "Id\030\002 \002(\014B\\\n>org.locationtech.geowave.dat" +
      "astore.hbase.coprocessors.protobufB\022Filt" +
      "erProtosClientH\001\210\001\001\240\001\001"
    };
    org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public org.apache.hadoop.hbase.shaded.com.google.protobuf.ExtensionRegistry assignDescriptors(
            org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SingleEntryFilter_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SingleEntryFilter_fieldAccessorTable = new
            org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SingleEntryFilter_descriptor,
              new java.lang.String[] { "AdapterId", "DataId", });
          return null;
        }
      };
    org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new org.apache.hadoop.hbase.shaded.com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
