// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SampleModel.proto

package org.locationtech.geowave.adapter.raster.protobuf;

public final class SampleModelProtos {
  private SampleModelProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SampleModelOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 modelType = 1;
    /**
     * <code>required uint32 modelType = 1;</code>
     */
    boolean hasModelType();
    /**
     * <code>required uint32 modelType = 1;</code>
     */
    int getModelType();

    // required uint32 transferType = 2;
    /**
     * <code>required uint32 transferType = 2;</code>
     */
    boolean hasTransferType();
    /**
     * <code>required uint32 transferType = 2;</code>
     */
    int getTransferType();

    // required uint32 width = 3;
    /**
     * <code>required uint32 width = 3;</code>
     */
    boolean hasWidth();
    /**
     * <code>required uint32 width = 3;</code>
     */
    int getWidth();

    // required uint32 height = 4;
    /**
     * <code>required uint32 height = 4;</code>
     */
    boolean hasHeight();
    /**
     * <code>required uint32 height = 4;</code>
     */
    int getHeight();

    // required uint32 scanlineStride = 5;
    /**
     * <code>required uint32 scanlineStride = 5;</code>
     */
    boolean hasScanlineStride();
    /**
     * <code>required uint32 scanlineStride = 5;</code>
     */
    int getScanlineStride();

    // optional uint32 pixelStride = 6;
    /**
     * <code>optional uint32 pixelStride = 6;</code>
     */
    boolean hasPixelStride();
    /**
     * <code>optional uint32 pixelStride = 6;</code>
     */
    int getPixelStride();

    // optional uint32 pixelBitStride = 7;
    /**
     * <code>optional uint32 pixelBitStride = 7;</code>
     */
    boolean hasPixelBitStride();
    /**
     * <code>optional uint32 pixelBitStride = 7;</code>
     */
    int getPixelBitStride();

    // optional uint32 dataBitOffset = 8;
    /**
     * <code>optional uint32 dataBitOffset = 8;</code>
     */
    boolean hasDataBitOffset();
    /**
     * <code>optional uint32 dataBitOffset = 8;</code>
     */
    int getDataBitOffset();

    // repeated uint32 bandOffsets = 9 [packed = true];
    /**
     * <code>repeated uint32 bandOffsets = 9 [packed = true];</code>
     */
    java.util.List<java.lang.Integer> getBandOffsetsList();
    /**
     * <code>repeated uint32 bandOffsets = 9 [packed = true];</code>
     */
    int getBandOffsetsCount();
    /**
     * <code>repeated uint32 bandOffsets = 9 [packed = true];</code>
     */
    int getBandOffsets(int index);

    // repeated uint32 bankIndices = 10 [packed = true];
    /**
     * <code>repeated uint32 bankIndices = 10 [packed = true];</code>
     */
    java.util.List<java.lang.Integer> getBankIndicesList();
    /**
     * <code>repeated uint32 bankIndices = 10 [packed = true];</code>
     */
    int getBankIndicesCount();
    /**
     * <code>repeated uint32 bankIndices = 10 [packed = true];</code>
     */
    int getBankIndices(int index);

    // repeated uint32 bitMasks = 11 [packed = true];
    /**
     * <code>repeated uint32 bitMasks = 11 [packed = true];</code>
     */
    java.util.List<java.lang.Integer> getBitMasksList();
    /**
     * <code>repeated uint32 bitMasks = 11 [packed = true];</code>
     */
    int getBitMasksCount();
    /**
     * <code>repeated uint32 bitMasks = 11 [packed = true];</code>
     */
    int getBitMasks(int index);
  }
  /**
   * Protobuf type {@code SampleModel}
   */
  public static final class SampleModel extends
      com.google.protobuf.GeneratedMessage
      implements SampleModelOrBuilder {
    // Use SampleModel.newBuilder() to construct.
    private SampleModel(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SampleModel(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SampleModel defaultInstance;
    public static SampleModel getDefaultInstance() {
      return defaultInstance;
    }

    public SampleModel getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SampleModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              modelType_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              transferType_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              width_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              height_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              scanlineStride_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              pixelStride_ = input.readUInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              pixelBitStride_ = input.readUInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              dataBitOffset_ = input.readUInt32();
              break;
            }
            case 72: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                bandOffsets_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000100;
              }
              bandOffsets_.add(input.readUInt32());
              break;
            }
            case 74: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100) && input.getBytesUntilLimit() > 0) {
                bandOffsets_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000100;
              }
              while (input.getBytesUntilLimit() > 0) {
                bandOffsets_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 80: {
              if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
                bankIndices_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000200;
              }
              bankIndices_.add(input.readUInt32());
              break;
            }
            case 82: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000200) == 0x00000200) && input.getBytesUntilLimit() > 0) {
                bankIndices_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000200;
              }
              while (input.getBytesUntilLimit() > 0) {
                bankIndices_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 88: {
              if (!((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
                bitMasks_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000400;
              }
              bitMasks_.add(input.readUInt32());
              break;
            }
            case 90: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000400) == 0x00000400) && input.getBytesUntilLimit() > 0) {
                bitMasks_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000400;
              }
              while (input.getBytesUntilLimit() > 0) {
                bitMasks_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          bandOffsets_ = java.util.Collections.unmodifiableList(bandOffsets_);
        }
        if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
          bankIndices_ = java.util.Collections.unmodifiableList(bankIndices_);
        }
        if (((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
          bitMasks_ = java.util.Collections.unmodifiableList(bitMasks_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.internal_static_SampleModel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.internal_static_SampleModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel.class, org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel.Builder.class);
    }

    public static com.google.protobuf.Parser<SampleModel> PARSER =
        new com.google.protobuf.AbstractParser<SampleModel>() {
      public SampleModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SampleModel(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SampleModel> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 modelType = 1;
    public static final int MODELTYPE_FIELD_NUMBER = 1;
    private int modelType_;
    /**
     * <code>required uint32 modelType = 1;</code>
     */
    public boolean hasModelType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 modelType = 1;</code>
     */
    public int getModelType() {
      return modelType_;
    }

    // required uint32 transferType = 2;
    public static final int TRANSFERTYPE_FIELD_NUMBER = 2;
    private int transferType_;
    /**
     * <code>required uint32 transferType = 2;</code>
     */
    public boolean hasTransferType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 transferType = 2;</code>
     */
    public int getTransferType() {
      return transferType_;
    }

    // required uint32 width = 3;
    public static final int WIDTH_FIELD_NUMBER = 3;
    private int width_;
    /**
     * <code>required uint32 width = 3;</code>
     */
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 width = 3;</code>
     */
    public int getWidth() {
      return width_;
    }

    // required uint32 height = 4;
    public static final int HEIGHT_FIELD_NUMBER = 4;
    private int height_;
    /**
     * <code>required uint32 height = 4;</code>
     */
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 height = 4;</code>
     */
    public int getHeight() {
      return height_;
    }

    // required uint32 scanlineStride = 5;
    public static final int SCANLINESTRIDE_FIELD_NUMBER = 5;
    private int scanlineStride_;
    /**
     * <code>required uint32 scanlineStride = 5;</code>
     */
    public boolean hasScanlineStride() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required uint32 scanlineStride = 5;</code>
     */
    public int getScanlineStride() {
      return scanlineStride_;
    }

    // optional uint32 pixelStride = 6;
    public static final int PIXELSTRIDE_FIELD_NUMBER = 6;
    private int pixelStride_;
    /**
     * <code>optional uint32 pixelStride = 6;</code>
     */
    public boolean hasPixelStride() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint32 pixelStride = 6;</code>
     */
    public int getPixelStride() {
      return pixelStride_;
    }

    // optional uint32 pixelBitStride = 7;
    public static final int PIXELBITSTRIDE_FIELD_NUMBER = 7;
    private int pixelBitStride_;
    /**
     * <code>optional uint32 pixelBitStride = 7;</code>
     */
    public boolean hasPixelBitStride() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint32 pixelBitStride = 7;</code>
     */
    public int getPixelBitStride() {
      return pixelBitStride_;
    }

    // optional uint32 dataBitOffset = 8;
    public static final int DATABITOFFSET_FIELD_NUMBER = 8;
    private int dataBitOffset_;
    /**
     * <code>optional uint32 dataBitOffset = 8;</code>
     */
    public boolean hasDataBitOffset() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional uint32 dataBitOffset = 8;</code>
     */
    public int getDataBitOffset() {
      return dataBitOffset_;
    }

    // repeated uint32 bandOffsets = 9 [packed = true];
    public static final int BANDOFFSETS_FIELD_NUMBER = 9;
    private java.util.List<java.lang.Integer> bandOffsets_;
    /**
     * <code>repeated uint32 bandOffsets = 9 [packed = true];</code>
     */
    public java.util.List<java.lang.Integer>
        getBandOffsetsList() {
      return bandOffsets_;
    }
    /**
     * <code>repeated uint32 bandOffsets = 9 [packed = true];</code>
     */
    public int getBandOffsetsCount() {
      return bandOffsets_.size();
    }
    /**
     * <code>repeated uint32 bandOffsets = 9 [packed = true];</code>
     */
    public int getBandOffsets(int index) {
      return bandOffsets_.get(index);
    }
    private int bandOffsetsMemoizedSerializedSize = -1;

    // repeated uint32 bankIndices = 10 [packed = true];
    public static final int BANKINDICES_FIELD_NUMBER = 10;
    private java.util.List<java.lang.Integer> bankIndices_;
    /**
     * <code>repeated uint32 bankIndices = 10 [packed = true];</code>
     */
    public java.util.List<java.lang.Integer>
        getBankIndicesList() {
      return bankIndices_;
    }
    /**
     * <code>repeated uint32 bankIndices = 10 [packed = true];</code>
     */
    public int getBankIndicesCount() {
      return bankIndices_.size();
    }
    /**
     * <code>repeated uint32 bankIndices = 10 [packed = true];</code>
     */
    public int getBankIndices(int index) {
      return bankIndices_.get(index);
    }
    private int bankIndicesMemoizedSerializedSize = -1;

    // repeated uint32 bitMasks = 11 [packed = true];
    public static final int BITMASKS_FIELD_NUMBER = 11;
    private java.util.List<java.lang.Integer> bitMasks_;
    /**
     * <code>repeated uint32 bitMasks = 11 [packed = true];</code>
     */
    public java.util.List<java.lang.Integer>
        getBitMasksList() {
      return bitMasks_;
    }
    /**
     * <code>repeated uint32 bitMasks = 11 [packed = true];</code>
     */
    public int getBitMasksCount() {
      return bitMasks_.size();
    }
    /**
     * <code>repeated uint32 bitMasks = 11 [packed = true];</code>
     */
    public int getBitMasks(int index) {
      return bitMasks_.get(index);
    }
    private int bitMasksMemoizedSerializedSize = -1;

    private void initFields() {
      modelType_ = 0;
      transferType_ = 0;
      width_ = 0;
      height_ = 0;
      scanlineStride_ = 0;
      pixelStride_ = 0;
      pixelBitStride_ = 0;
      dataBitOffset_ = 0;
      bandOffsets_ = java.util.Collections.emptyList();
      bankIndices_ = java.util.Collections.emptyList();
      bitMasks_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasModelType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTransferType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWidth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScanlineStride()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, modelType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, transferType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, width_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, height_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, scanlineStride_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, pixelStride_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt32(7, pixelBitStride_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt32(8, dataBitOffset_);
      }
      if (getBandOffsetsList().size() > 0) {
        output.writeRawVarint32(74);
        output.writeRawVarint32(bandOffsetsMemoizedSerializedSize);
      }
      for (int i = 0; i < bandOffsets_.size(); i++) {
        output.writeUInt32NoTag(bandOffsets_.get(i));
      }
      if (getBankIndicesList().size() > 0) {
        output.writeRawVarint32(82);
        output.writeRawVarint32(bankIndicesMemoizedSerializedSize);
      }
      for (int i = 0; i < bankIndices_.size(); i++) {
        output.writeUInt32NoTag(bankIndices_.get(i));
      }
      if (getBitMasksList().size() > 0) {
        output.writeRawVarint32(90);
        output.writeRawVarint32(bitMasksMemoizedSerializedSize);
      }
      for (int i = 0; i < bitMasks_.size(); i++) {
        output.writeUInt32NoTag(bitMasks_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, modelType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, transferType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, width_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, height_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, scanlineStride_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, pixelStride_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, pixelBitStride_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, dataBitOffset_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < bandOffsets_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(bandOffsets_.get(i));
        }
        size += dataSize;
        if (!getBandOffsetsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        bandOffsetsMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < bankIndices_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(bankIndices_.get(i));
        }
        size += dataSize;
        if (!getBankIndicesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        bankIndicesMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < bitMasks_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(bitMasks_.get(i));
        }
        size += dataSize;
        if (!getBitMasksList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        bitMasksMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SampleModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.internal_static_SampleModel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.internal_static_SampleModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel.class, org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel.Builder.class);
      }

      // Construct using org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        modelType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        transferType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        width_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        height_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        scanlineStride_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        pixelStride_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        pixelBitStride_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        dataBitOffset_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        bandOffsets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        bankIndices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);
        bitMasks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.internal_static_SampleModel_descriptor;
      }

      public org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel getDefaultInstanceForType() {
        return org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel.getDefaultInstance();
      }

      public org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel build() {
        org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel buildPartial() {
        org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel result = new org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.modelType_ = modelType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.transferType_ = transferType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.width_ = width_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.height_ = height_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.scanlineStride_ = scanlineStride_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.pixelStride_ = pixelStride_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.pixelBitStride_ = pixelBitStride_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.dataBitOffset_ = dataBitOffset_;
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          bandOffsets_ = java.util.Collections.unmodifiableList(bandOffsets_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.bandOffsets_ = bandOffsets_;
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          bankIndices_ = java.util.Collections.unmodifiableList(bankIndices_);
          bitField0_ = (bitField0_ & ~0x00000200);
        }
        result.bankIndices_ = bankIndices_;
        if (((bitField0_ & 0x00000400) == 0x00000400)) {
          bitMasks_ = java.util.Collections.unmodifiableList(bitMasks_);
          bitField0_ = (bitField0_ & ~0x00000400);
        }
        result.bitMasks_ = bitMasks_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel) {
          return mergeFrom((org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel other) {
        if (other == org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel.getDefaultInstance()) return this;
        if (other.hasModelType()) {
          setModelType(other.getModelType());
        }
        if (other.hasTransferType()) {
          setTransferType(other.getTransferType());
        }
        if (other.hasWidth()) {
          setWidth(other.getWidth());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        if (other.hasScanlineStride()) {
          setScanlineStride(other.getScanlineStride());
        }
        if (other.hasPixelStride()) {
          setPixelStride(other.getPixelStride());
        }
        if (other.hasPixelBitStride()) {
          setPixelBitStride(other.getPixelBitStride());
        }
        if (other.hasDataBitOffset()) {
          setDataBitOffset(other.getDataBitOffset());
        }
        if (!other.bandOffsets_.isEmpty()) {
          if (bandOffsets_.isEmpty()) {
            bandOffsets_ = other.bandOffsets_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureBandOffsetsIsMutable();
            bandOffsets_.addAll(other.bandOffsets_);
          }
          onChanged();
        }
        if (!other.bankIndices_.isEmpty()) {
          if (bankIndices_.isEmpty()) {
            bankIndices_ = other.bankIndices_;
            bitField0_ = (bitField0_ & ~0x00000200);
          } else {
            ensureBankIndicesIsMutable();
            bankIndices_.addAll(other.bankIndices_);
          }
          onChanged();
        }
        if (!other.bitMasks_.isEmpty()) {
          if (bitMasks_.isEmpty()) {
            bitMasks_ = other.bitMasks_;
            bitField0_ = (bitField0_ & ~0x00000400);
          } else {
            ensureBitMasksIsMutable();
            bitMasks_.addAll(other.bitMasks_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasModelType()) {
          
          return false;
        }
        if (!hasTransferType()) {
          
          return false;
        }
        if (!hasWidth()) {
          
          return false;
        }
        if (!hasHeight()) {
          
          return false;
        }
        if (!hasScanlineStride()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.locationtech.geowave.adapter.raster.protobuf.SampleModelProtos.SampleModel) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 modelType = 1;
      private int modelType_ ;
      /**
       * <code>required uint32 modelType = 1;</code>
       */
      public boolean hasModelType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 modelType = 1;</code>
       */
      public int getModelType() {
        return modelType_;
      }
      /**
       * <code>required uint32 modelType = 1;</code>
       */
      public Builder setModelType(int value) {
        bitField0_ |= 0x00000001;
        modelType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 modelType = 1;</code>
       */
      public Builder clearModelType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        modelType_ = 0;
        onChanged();
        return this;
      }

      // required uint32 transferType = 2;
      private int transferType_ ;
      /**
       * <code>required uint32 transferType = 2;</code>
       */
      public boolean hasTransferType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 transferType = 2;</code>
       */
      public int getTransferType() {
        return transferType_;
      }
      /**
       * <code>required uint32 transferType = 2;</code>
       */
      public Builder setTransferType(int value) {
        bitField0_ |= 0x00000002;
        transferType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 transferType = 2;</code>
       */
      public Builder clearTransferType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        transferType_ = 0;
        onChanged();
        return this;
      }

      // required uint32 width = 3;
      private int width_ ;
      /**
       * <code>required uint32 width = 3;</code>
       */
      public boolean hasWidth() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 width = 3;</code>
       */
      public int getWidth() {
        return width_;
      }
      /**
       * <code>required uint32 width = 3;</code>
       */
      public Builder setWidth(int value) {
        bitField0_ |= 0x00000004;
        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 width = 3;</code>
       */
      public Builder clearWidth() {
        bitField0_ = (bitField0_ & ~0x00000004);
        width_ = 0;
        onChanged();
        return this;
      }

      // required uint32 height = 4;
      private int height_ ;
      /**
       * <code>required uint32 height = 4;</code>
       */
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 height = 4;</code>
       */
      public int getHeight() {
        return height_;
      }
      /**
       * <code>required uint32 height = 4;</code>
       */
      public Builder setHeight(int value) {
        bitField0_ |= 0x00000008;
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 height = 4;</code>
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000008);
        height_ = 0;
        onChanged();
        return this;
      }

      // required uint32 scanlineStride = 5;
      private int scanlineStride_ ;
      /**
       * <code>required uint32 scanlineStride = 5;</code>
       */
      public boolean hasScanlineStride() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required uint32 scanlineStride = 5;</code>
       */
      public int getScanlineStride() {
        return scanlineStride_;
      }
      /**
       * <code>required uint32 scanlineStride = 5;</code>
       */
      public Builder setScanlineStride(int value) {
        bitField0_ |= 0x00000010;
        scanlineStride_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 scanlineStride = 5;</code>
       */
      public Builder clearScanlineStride() {
        bitField0_ = (bitField0_ & ~0x00000010);
        scanlineStride_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 pixelStride = 6;
      private int pixelStride_ ;
      /**
       * <code>optional uint32 pixelStride = 6;</code>
       */
      public boolean hasPixelStride() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint32 pixelStride = 6;</code>
       */
      public int getPixelStride() {
        return pixelStride_;
      }
      /**
       * <code>optional uint32 pixelStride = 6;</code>
       */
      public Builder setPixelStride(int value) {
        bitField0_ |= 0x00000020;
        pixelStride_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 pixelStride = 6;</code>
       */
      public Builder clearPixelStride() {
        bitField0_ = (bitField0_ & ~0x00000020);
        pixelStride_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 pixelBitStride = 7;
      private int pixelBitStride_ ;
      /**
       * <code>optional uint32 pixelBitStride = 7;</code>
       */
      public boolean hasPixelBitStride() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional uint32 pixelBitStride = 7;</code>
       */
      public int getPixelBitStride() {
        return pixelBitStride_;
      }
      /**
       * <code>optional uint32 pixelBitStride = 7;</code>
       */
      public Builder setPixelBitStride(int value) {
        bitField0_ |= 0x00000040;
        pixelBitStride_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 pixelBitStride = 7;</code>
       */
      public Builder clearPixelBitStride() {
        bitField0_ = (bitField0_ & ~0x00000040);
        pixelBitStride_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 dataBitOffset = 8;
      private int dataBitOffset_ ;
      /**
       * <code>optional uint32 dataBitOffset = 8;</code>
       */
      public boolean hasDataBitOffset() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional uint32 dataBitOffset = 8;</code>
       */
      public int getDataBitOffset() {
        return dataBitOffset_;
      }
      /**
       * <code>optional uint32 dataBitOffset = 8;</code>
       */
      public Builder setDataBitOffset(int value) {
        bitField0_ |= 0x00000080;
        dataBitOffset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 dataBitOffset = 8;</code>
       */
      public Builder clearDataBitOffset() {
        bitField0_ = (bitField0_ & ~0x00000080);
        dataBitOffset_ = 0;
        onChanged();
        return this;
      }

      // repeated uint32 bandOffsets = 9 [packed = true];
      private java.util.List<java.lang.Integer> bandOffsets_ = java.util.Collections.emptyList();
      private void ensureBandOffsetsIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          bandOffsets_ = new java.util.ArrayList<java.lang.Integer>(bandOffsets_);
          bitField0_ |= 0x00000100;
         }
      }
      /**
       * <code>repeated uint32 bandOffsets = 9 [packed = true];</code>
       */
      public java.util.List<java.lang.Integer>
          getBandOffsetsList() {
        return java.util.Collections.unmodifiableList(bandOffsets_);
      }
      /**
       * <code>repeated uint32 bandOffsets = 9 [packed = true];</code>
       */
      public int getBandOffsetsCount() {
        return bandOffsets_.size();
      }
      /**
       * <code>repeated uint32 bandOffsets = 9 [packed = true];</code>
       */
      public int getBandOffsets(int index) {
        return bandOffsets_.get(index);
      }
      /**
       * <code>repeated uint32 bandOffsets = 9 [packed = true];</code>
       */
      public Builder setBandOffsets(
          int index, int value) {
        ensureBandOffsetsIsMutable();
        bandOffsets_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 bandOffsets = 9 [packed = true];</code>
       */
      public Builder addBandOffsets(int value) {
        ensureBandOffsetsIsMutable();
        bandOffsets_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 bandOffsets = 9 [packed = true];</code>
       */
      public Builder addAllBandOffsets(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureBandOffsetsIsMutable();
        super.addAll(values, bandOffsets_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 bandOffsets = 9 [packed = true];</code>
       */
      public Builder clearBandOffsets() {
        bandOffsets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }

      // repeated uint32 bankIndices = 10 [packed = true];
      private java.util.List<java.lang.Integer> bankIndices_ = java.util.Collections.emptyList();
      private void ensureBankIndicesIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          bankIndices_ = new java.util.ArrayList<java.lang.Integer>(bankIndices_);
          bitField0_ |= 0x00000200;
         }
      }
      /**
       * <code>repeated uint32 bankIndices = 10 [packed = true];</code>
       */
      public java.util.List<java.lang.Integer>
          getBankIndicesList() {
        return java.util.Collections.unmodifiableList(bankIndices_);
      }
      /**
       * <code>repeated uint32 bankIndices = 10 [packed = true];</code>
       */
      public int getBankIndicesCount() {
        return bankIndices_.size();
      }
      /**
       * <code>repeated uint32 bankIndices = 10 [packed = true];</code>
       */
      public int getBankIndices(int index) {
        return bankIndices_.get(index);
      }
      /**
       * <code>repeated uint32 bankIndices = 10 [packed = true];</code>
       */
      public Builder setBankIndices(
          int index, int value) {
        ensureBankIndicesIsMutable();
        bankIndices_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 bankIndices = 10 [packed = true];</code>
       */
      public Builder addBankIndices(int value) {
        ensureBankIndicesIsMutable();
        bankIndices_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 bankIndices = 10 [packed = true];</code>
       */
      public Builder addAllBankIndices(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureBankIndicesIsMutable();
        super.addAll(values, bankIndices_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 bankIndices = 10 [packed = true];</code>
       */
      public Builder clearBankIndices() {
        bankIndices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }

      // repeated uint32 bitMasks = 11 [packed = true];
      private java.util.List<java.lang.Integer> bitMasks_ = java.util.Collections.emptyList();
      private void ensureBitMasksIsMutable() {
        if (!((bitField0_ & 0x00000400) == 0x00000400)) {
          bitMasks_ = new java.util.ArrayList<java.lang.Integer>(bitMasks_);
          bitField0_ |= 0x00000400;
         }
      }
      /**
       * <code>repeated uint32 bitMasks = 11 [packed = true];</code>
       */
      public java.util.List<java.lang.Integer>
          getBitMasksList() {
        return java.util.Collections.unmodifiableList(bitMasks_);
      }
      /**
       * <code>repeated uint32 bitMasks = 11 [packed = true];</code>
       */
      public int getBitMasksCount() {
        return bitMasks_.size();
      }
      /**
       * <code>repeated uint32 bitMasks = 11 [packed = true];</code>
       */
      public int getBitMasks(int index) {
        return bitMasks_.get(index);
      }
      /**
       * <code>repeated uint32 bitMasks = 11 [packed = true];</code>
       */
      public Builder setBitMasks(
          int index, int value) {
        ensureBitMasksIsMutable();
        bitMasks_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 bitMasks = 11 [packed = true];</code>
       */
      public Builder addBitMasks(int value) {
        ensureBitMasksIsMutable();
        bitMasks_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 bitMasks = 11 [packed = true];</code>
       */
      public Builder addAllBitMasks(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureBitMasksIsMutable();
        super.addAll(values, bitMasks_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 bitMasks = 11 [packed = true];</code>
       */
      public Builder clearBitMasks() {
        bitMasks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000400);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SampleModel)
    }

    static {
      defaultInstance = new SampleModel(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SampleModel)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SampleModel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SampleModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021SampleModel.proto\"\371\001\n\013SampleModel\022\021\n\tm" +
      "odelType\030\001 \002(\r\022\024\n\014transferType\030\002 \002(\r\022\r\n\005" +
      "width\030\003 \002(\r\022\016\n\006height\030\004 \002(\r\022\026\n\016scanlineS" +
      "tride\030\005 \002(\r\022\023\n\013pixelStride\030\006 \001(\r\022\026\n\016pixe" +
      "lBitStride\030\007 \001(\r\022\025\n\rdataBitOffset\030\010 \001(\r\022" +
      "\027\n\013bandOffsets\030\t \003(\rB\002\020\001\022\027\n\013bankIndices\030" +
      "\n \003(\rB\002\020\001\022\024\n\010bitMasks\030\013 \003(\rB\002\020\001BG\n0org.l" +
      "ocationtech.geowave.adapter.raster.proto" +
      "bufB\021SampleModelProtosH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SampleModel_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SampleModel_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SampleModel_descriptor,
              new java.lang.String[] { "ModelType", "TransferType", "Width", "Height", "ScanlineStride", "PixelStride", "PixelBitStride", "DataBitOffset", "BandOffsets", "BankIndices", "BitMasks", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
