name: GeoWave Build
on: [push, pull_request]
env:
    DEV_RESOURCES_VERSION: 1.7
    MAVEN_PROFILES: '""'
    BUILD_AND_PUBLISH: false
    IT_ONLY: true
    MAVEN_OPTS: "-XX:CompressedClassSpaceSize=256m -XX:+UseSerialGC -Xmx2g -XX:MaxMetaspaceSize=512m -Dorg.slf4j.simpleLogger.defaultLogLevel=warn"
    
jobs:
    unit-tests:
        runs-on: ubuntu-16.04
        name: Unit Tests on Latest ASF Versions
        env:
            IT_ONLY: false
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              
            - name: Cache resources
              uses: actions/cache@v2
              env:
                cache-name: cache-geowave-resources
              with:
                key:  ${{ runner.os }}
                path: |
                      ~/.m2
                      ~/.downloads
                      test/landsat8
                      test/sentinel2
                      test/target/temp/gdal
            - name: Run
              run: ./.utility/run-all.sh
            - name: Publish Test Report
              uses: scacap/action-surefire-report@v1
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                fail_on_test_failures: true
             