name: Tests
on: [push, pull_request]
env:
    DEV_RESOURCES_VERSION: 1.7
    MAVEN_PROFILES: '""'
    IT_ONLY: true
    MAVEN_OPTS: "-XX:CompressedClassSpaceSize=256m -XX:+UseSerialGC -Xmx2g -XX:MaxMetaspaceSize=512m -Dorg.slf4j.simpleLogger.defaultLogLevel=warn"    
jobs:   
    integration-tests:
        runs-on: ubuntu-18.04
        name: ${{ matrix.profile }} Integration Tests 
        strategy:
            fail-fast: false
            matrix:
                profile: [kudu-it]
        env:
            IT_ONLY: true
            MAVEN_PROFILES: ${{ matrix.profile }}
            TEST_KERBEROS: ${{ matrix.test_kerberos }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              
            - name: Set up AdoptOpenJDK 1.8
              uses: joschi/setup-jdk@v2
              with:
                java-version: '8' 
                architecture: x64  
                
            - name: Set up Maven
              uses: stCarolas/setup-maven@v4
              with:
                maven-version: 3.6.3
              
                
            - name: Cache maven resources
              uses: actions/cache@v2
              env:
                cache-name: cache-maven-resources
              with:
                key: ${{ runner.os }}-mvn-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                      ${{ runner.os }}-mvn-
                path: |
                      ~/.m2/repository

            - name: Cache other resources
              uses: actions/cache@v2
              env:
                cache-name: cache-resources
              with:
                key: ${{ runner.os }}-other
                restore-keys: |
                      ${{ runner.os }}-other
                path: |  
                      ~/.downloads
                      test/landsat8
                      test/sentinel2
                      test/target/temp/gdal

            - name: Run
              run: ./.utility/run-tests.sh

            - name: Publish Integration Test ${{ matrix.profile }} Results
              uses: scacap/action-surefire-report@v1
              if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
              with:
                check_name: ${{ matrix.profile }} Results
                report_paths: test/target/failsafe-reports/TEST-org.locationtech.geowave.test.GeoWaveITSuite.xml
                github_token: ${{ secrets.GITHUB_TOKEN }}